/*******************************************************************************
 * Copyright (c) 2010 Oobium, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Jeremy Dowdall <jeremy@oobium.com> - initial API and implementation
 ******************************************************************************/
package org.oobium.persist;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface ModelDescription {

	public static final String ID = "id";

	public static final String CREATED_AT = "createdAt";
	public static final String UPDATED_AT = "updatedAt";
	public static final String CREATED_ON = "createdOn";
	public static final String UPDATED_ON = "updatedOn";

	/**
	 * If true, then this model will have the "activatedAt" and "activationCode" attributes.
	 * "activationCode" is a String that contains a unique token (generated by UUID) that can be
	 * used to activate this model (typically a User). "activatedAt" should contain the java.util.Date
	 * of when this model was successfully activated (presumably by comparing a received token with
	 * the "activationCode" - to be done by the application developer).
	 */
	boolean activation() default false;
	
	Attribute[] attrs() default {};
	Relation[] hasMany() default {};
	Relation[] hasOne() default {};
	
	/**
	 * If true, then this model will have "createdOn" and "updatedOn" attributes, both
	 * of type java.sql.Date. The fields will be automatically handled in the persist service.
	 */
	boolean datestamps() default false;

	/**
	 * If true, then this model will have "createdAt" and "updatedAt" attributes, both
	 * of type java.util.Date. The fields will be automatically handled in the persist service.
	 */
	boolean timestamps() default false;
	
	boolean allowDelete() default true;
	boolean allowUpdate() default true;

}
